### PR TITLE
Auto pip install

### PR DESCRIPTION
**Pull request by jiakunw**
I automated pip install but you have to manually set environmental variable.

### CODE REVIEW

**Comment by jiakunw** [comment]
The code I wrote ran successfully, but the later part did not becasue the cluster did not have cython installed. When I attempted to install cython I got permission errors:
WechatIMG473
WechatIMG470

**Comment by jiakunw** [comment]
This time I added requirement.txt. When I ran python setup.py install I got the following errors:
WechatIMG496
WechatIMG497
I also tried running pip.install mirage but I got some other errors:
WechatIMG498
WechatIMG499
WechatIMG500

**Comment by jiazhihao** [comment]
> This time I added requirement.txt. When I ran python setup.py install I got the following errors:

Make sure you compile on a GPU node (instead of the catalyst-cluster login node), since there is no GPUs on the login node. You can do so by running `salloc --nodes 1 --gres=gpu:1` and then ssh to the assigned node, which should be one of catalyst-0-9 ... catalyst-0-15.

> I also tried running pip.install mirage but I got some other errors:

I am not 100% how to resolve this issue.

**Comment by jiakunw** [comment]
> nce there is no GPUs on the login node. You can do so by running `salloc --nodes 1 --gres=gpu:1` and then ssh to the assigned node, which should be one of catalyst-0-9 ... catalyst-0-15.

I tried this but I got different error messages when running pip3 install: 
pipipip

I also tried cd into python and run python3 setup.py install and I got the same cython permission denied error as before.

**Comment by jiakunw** [comment]
I fixed some bugs but _cython is not in mirage
ccc

**Comment by jiakunw** [comment]
I tried running the commands maually using the unmodified verison of setup.py as specified in INSTALL.md, and I got the same error message. Using pdb I realized the error message came from ```python
return cythonize(ret, compiler_directives={"language_level" : 3})
WechatIMG610
could you please take a look at ```config_cython()  ?

**Comment by jiakunw** [comment]
I tried running the commands maually using the unmodified verison of setup.py as specified in INSTALL.md, and I got the same error message. Using pdb I realized the error message came from python return cythonize(ret, compiler_directives={"language_level" : 3})’‘’ WechatIMG610 could you please take a look at config_cython()‘’‘ ?

**Comment by jiakunw** [comment]
I tried running the commands maually using the unmodified verison of setup.py as specified in INSTALL.md, and I got the same error message. Using pdb I realized the error message came from ```python
 return cythonize(ret, compiler_directives={"language_level" : 3})``` WechatIMG610 could you please take a look at ```config_cython() ```?

**Comment by jiakunw** [comment]
does that mean it worked?
WechatIMG341
I also have some questions about it. cuDNN and CUDA is not available as a Python package on PyPI. cuDNN is a GPU-accelerated library for deep neural networks provided by NVIDIA, and it should be installed via conda or directly from NVIDIA's website, not from PyPI. So I removed cuda and cudnn version from requirements.txt, but they are both installed, and it seemed working. Does that mean it's done or I should fix them??

**Comment by jiazhihao** [comment]
@jiakunw Thanks for the PR. One quick comment: you may not want to include your personal vscode config in this PR: vscode/sftp.json.

**Comment by jiakunw** [comment]
fixed!

**Comment by jiazhihao** [comment]
The PR looks great overall. One last thing: you can use `git rm` to remove the sftp.json file and run `script/format.sh` to auto-format your changes.

**Comment by jiakunw** [comment]
> script/format.sh

'(base) jackiexu@Jackies-MacBook-Pro mirage % scripts/format.sh
scripts/format.sh: line 71: mapfile: command not found' I got this error when I ran it

**Comment by jiazhihao** [comment]
I can correct format in another PR. Can you use git rm to remove your json file from this PR.

**Comment by jiakunw** [comment]
I removed it yesterday and there was no json file in the repo
WechatIMG58
WechatIMG59

**Comment by jiazhihao** [comment]
It is still there in this PR: https://github.com/mirage-project/mirage/pull/20/files. Let me push a fix to address this issue.

**Comment by jiakunw** [comment]
I re-removed it, it should be good for now :)

**Review by jiazhihao — APPROVED** [review]

**Comment by jiazhihao** [comment]
merged. Great work!

**Pull request merged**
